---
- name: Reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded

- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: Restart molly-brown
  ansible.builtin.systemd:
    name: molly-brown@molly-brown
    state: restarted

- name: Restart gophernicus
  ansible.builtin.systemd:
    name: gophernicus
    state: restarted
